name: help4you
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Aesthetics
  animations: ^2.0.10
  google_fonts: ^6.1.0
  flare_flutter: ^3.0.2
  awesome_dialog: ^3.1.0
  cupertino_icons: ^1.0.6
  page_transition: ^2.1.0
  fluentui_system_icons: ^1.1.223

  # Widgets
  pinput: ^3.0.1
  flutter_svg: ^2.0.9
  rate_my_app: ^2.0.0
  table_calendar: ^3.0.9
  flutter_spinkit: ^5.2.0
  intl_phone_field: ^3.2.0
  sliding_up_panel: ^2.0.0+1
  simple_star_rating: ^0.0.3
  google_maps_flutter: ^2.5.0
  flutter_time_picker_spinner: ^2.0.0

  # Features
  intl: ^0.18.0
  clipboard: ^0.1.3
  share_plus: ^7.2.1
  url_launcher: ^6.2.2
  image_cropper: ^5.0.1
  image_picker: ^1.0.5
  device_info_plus: ^9.1.1
  flutter_slidable: ^3.0.1
  flutter_markdown: ^0.6.18+2
  image_downloader: ^0.31.0
  permission_handler: ^11.1.0
  visibility_detector: ^0.4.0+2
  cached_network_image: ^3.3.0
  random_string_generator: ^2.0.0
  custom_full_image_screen: ^0.0.4
  flutter_phone_direct_caller: ^2.1.1
  internet_connection_checker: ^1.0.0+1

  # Database Utilities
  provider: ^6.1.1
  geolocator: ^10.1.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter Lint
  flutter_lints: ^2.0.1

  # Launcher Icon
  flutter_launcher_icons: ^0.13.1

  # Native Launch Screen
  flutter_native_splash: ^2.2.3

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/Help4You_App_Logo_v02.png"
  image_path_android: "assets/images/Help4You_App_Logo_v02.png"
  adaptive_icon_background: "assets/images/Help4You_App_Logo_v02_Android_Adaptive_Background.png"
  adaptive_icon_foreground: "assets/images/Help4You_App_Logo_v02_Android_Adaptive_Foreground.png"

flutter_native_splash:
  ios: true
  android: true
  color: "#FFFFFF"
  image: "assets/images/Help4You_App_Logo_v02_Transparent.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Files
    - assets/files/terms_and_conditions.md
    - assets/files/privacy_policy.md
    - assets/files/about_help4you.md
    # Flares
    - assets/flares/Success_Flare_Without_Loop.flr
    # Graphics
    - assets/graphics/Help4You_Illustration_1.svg
    - assets/graphics/Help4You_Illustration_2.svg
    - assets/graphics/Help4You_Illustration_3.svg
    - assets/graphics/Help4You_Illustration_4.svg
    - assets/graphics/Help4You_Illustration_6.svg
    - assets/graphics/Help4You_Illustration_7.svg
    - assets/graphics/Help4You_Illustration_8.svg
    # Images
    - assets/images/Help4You_App_Logo_v02.png
    - assets/images/Help4You_App_Logo_v02_Transparent.png
    - assets/images/Help4You_App_Logo_v02_Android_Adaptive_Foreground.png
    - assets/images/Help4You_App_Logo_v02_Android_Adaptive_Background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
