name: help4you
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Aesthetics
  animations: ^2.0.2
  flare_flutter: ^3.0.2
  awesome_dialog: ^2.1.2
  cupertino_icons: ^1.0.4
  page_transition: ^2.0.4
  fluentui_system_icons: ^1.1.153
  
  # Widgets
  pinput: ^1.2.2
  flutter_svg: ^1.0.0
  rate_my_app: ^1.1.1+1
  table_calendar: ^3.0.3
  intl_phone_field: ^2.1.0
  sliding_up_panel: ^2.0.0+1
  simple_star_rating: ^0.0.3
  google_maps_flutter: ^2.1.1
  flutter_time_picker_spinner: ^2.0.0

  # Features
  intl: ^0.17.0
  share: ^2.0.4
  clipboard: ^0.1.3
  url_launcher: ^6.0.17
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  device_info_plus: ^3.2.0
  flutter_slidable: ^1.1.0
  flutter_markdown: ^0.6.8
  image_downloader: ^0.31.0
  cached_network_image: ^3.2.0
  random_string_generator: ^2.0.0
  full_screen_image_null_safe: ^2.0.0
  flutter_phone_direct_caller: ^2.1.0
  internet_connection_checker: ^0.0.1+3

  # Database Utilities
  provider: ^6.0.1
  geolocator: ^8.0.0
  firebase_auth: ^3.3.0
  firebase_core: ^1.10.2
  cloud_firestore: ^3.1.1
  onesignal_flutter: ^3.3.1
  firebase_storage: ^10.2.0
  firebase_crashlytics: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Flutter App Name
  flutter_app_name: ^0.1.1

  # Launcher Icon
  flutter_launcher_icons: ^0.9.2

  # Native Launch Screen
  flutter_native_splash: ^1.3.2

flutter_app_name:
  name: "Help4You"

flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: 'assets/images/Help4You_App_Logo_v02.png'
  image_path_android: 'assets/images/Help4You_App_Logo_v02.png'
  adaptive_icon_background: 'assets/images/Help4You_App_Logo_v02_Android_Adaptive_Background.png'
  adaptive_icon_foreground: 'assets/images/Help4You_App_Logo_v02_Android_Adaptive_Foreground.png'

flutter_native_splash:
  ios: true
  android: true
  color: "#FFFFFF"
  image: "assets/images/Help4You_App_Logo_v02_Transparent.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # Files
    - assets/files/terms_and_conditions.md 
    - assets/files/privacy_policy.md
    - assets/files/about_help4you.md
    # Flares
    - assets/flares/Success_Flare_Without_Loop.flr
    # Graphics
    - assets/graphics/Help4You_Illustration_1.svg
    - assets/graphics/Help4You_Illustration_2.svg
    - assets/graphics/Help4You_Illustration_3.svg
    - assets/graphics/Help4You_Illustration_4.svg
    - assets/graphics/Help4You_Illustration_6.svg
    - assets/graphics/Help4You_Illustration_7.svg
    - assets/graphics/Help4You_Illustration_8.svg
    # Images
    - assets/images/Help4You_App_Logo_v02.png
    - assets/images/Help4You_App_Logo_v02_Transparent.png
    - assets/images/Help4You_App_Logo_v02_Android_Adaptive_Foreground.png
    - assets/images/Help4You_App_Logo_v02_Android_Adaptive_Background.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: BalooPaaji
      fonts:
        - asset: assets/fonts/BalooPaaji2-Regular.ttf
        - asset: assets/fonts/BalooPaaji2-Medium.ttf
          weight: 100
        - asset: assets/fonts/BalooPaaji2-SemiBold.ttf
          weight: 300
        - asset: assets/fonts/BalooPaaji2-Bold.ttf
          weight: 600
        - asset: assets/fonts/BalooPaaji2-ExtraBold.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
